In [1]:
import main

The data directory is ../data
Shapes of input-output sequences:
torch.Size([9, 1]) torch.Size([2, 1])
10
Input sentence: "terapiaa piti oottaa vuoden verran rivinvaihto miks taa systeemi EOS"
Sentence as tensor of word indices:
tensor([[4864],
        [1995],
        [4865],
        [4866],
        [3132],
        [   3],
        [2427],
        [  12],
        [4867],
        [   1]])

Output sentence: "heikkoo EOS"
Sentence as tensor of word indices:
tensor([[4771],
        [   1]])
Input sequences combined:
tensor([[6., 1.],
        [7., 2.],
        [8., 0.]])
Lengths: [3, 2]
Output sequences combined:
tensor([[ 9.,  3.],
        [10.,  4.],
        [ 0.,  5.]])
Lengths: [2, 3]
Shapes seem to be ok.
The shapes seem to be ok.
The shapes seem to be ok.
The shapes seem to be ok.
[1,   100] loss: 4.3106


KeyboardInterrupt: 